#feat: The new feature you're adding to a particular application
#fix: A bug fix
#style: Feature and updates related to styling
#refactor: Refactoring a specific section of the codebase
#test: Everything related to testing
#docs: Everything related to documentation
#chore: Regular code maintenance.
#from : https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/


# Feel free to change as per your liking.
[[keys]]
prefix = "feat"
description = "introduce new features"

[[keys]]
prefix = "fix"
description = "fix a bug"

[[keys]]
prefix = "style"
description = "updates and features related to styling"

[[keys]]
prefix = "refactor"
description = "refactor code"

[[keys]]
prefix = "test"
description = "add or update test"

[[keys]]
prefix = "docs"
description = "add or update documentation"

[[keys]]
prefix = "chore"
description = "regular maintenance"

# Messaging template
# Messages are broken down into 3 parts, prefix (%p), region (%r), message (%m)
# Two types of templates are needed, one with region and one without. Tell me know if a better way exist.
# No foolproofing has been done, yet. Might come across undefined behaviour.
[template]
region = "%p(%r): %m"
normal = "%p: %m"